/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin//': RouteRecordInfo<'/admin//', '/admin', Record<never, never>, Record<never, never>>,
    '/admin//options/': RouteRecordInfo<'/admin//options/', '/admin/options', Record<never, never>, Record<never, never>>,
    '/admin//questions/': RouteRecordInfo<'/admin//questions/', '/admin/questions', Record<never, never>, Record<never, never>>,
    '/admin//questions/[id]': RouteRecordInfo<'/admin//questions/[id]', '/admin/questions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin//quizzes/': RouteRecordInfo<'/admin//quizzes/', '/admin/quizzes', Record<never, never>, Record<never, never>>,
    '/admin//quizzes/[id]': RouteRecordInfo<'/admin//quizzes/[id]', '/admin/quizzes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin//sessions/': RouteRecordInfo<'/admin//sessions/', '/admin/sessions', Record<never, never>, Record<never, never>>,
    '/admin//sessions/[id]': RouteRecordInfo<'/admin//sessions/[id]', '/admin/sessions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin//sessions/[sessionId]/user.[userId]': RouteRecordInfo<'/admin//sessions/[sessionId]/user.[userId]', '/admin/sessions/:sessionId/user/:userId', { sessionId: ParamValue<true>, userId: ParamValue<true> }, { sessionId: ParamValue<false>, userId: ParamValue<false> }>,
    '/admin//sessions/result.[id]': RouteRecordInfo<'/admin//sessions/result.[id]', '/admin/sessions/result/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin//users/': RouteRecordInfo<'/admin//users/', '/admin/users', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
  }
}
